### ISSUE TITLE
No option to select Clock Source

### ISSUE THREAD

**Issue by skpang** [microchip-pic-avr-examples/pic18f57q84-can-fd-basic-operation-mplab-mcc#1]
I'm using MCC Melody Core v2.6.0
CAN FD driver v1.2.0

In the Clock Settings, there is no Clock Source option to select FOSC.
There is only Requested FCAN Frequency and Calculated FCAN Frequency.

Where is  Clock Source option ?

**Comment by pic-avr-github-admin** [comment]
The "Clock Source" selection is contained within "CAN1" rather than "CAN_FD1" where all of the other settings are contained.  Selecting CAN1 from the builder will give the window with the settings you're looking for
